version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  test-build-deploy:
    jobs:
      - build-and-deploy-dev:
          context: pa-aws-dev-deploy
          filters:
            branches:
              only:
                - development
                - staging

jobs:
  build-and-deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Create build artifact
          command: |
            mkdir build
            cp handler.js ./build
            cd build || exit
            zip -r ./$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH.zip .
      - aws-s3/copy:
          from: ./build/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BRANCH.zip
          to: 's3://$S3_CODE_BUCKET/$CIRCLE_PROJECT_REPONAME/'
          arguments: '--metadata Branch=$CIRCLE_BRANCH,Sha1=$CIRCLE_SHA1,Tag=$CIRCLE_TAG,PullRequestUrl=$CIRCLE_PULL_REQUEST'